In [5]:
from MOT import MOT
import numpy as np
import os
from BfTableGenerator import RansacCollector
from BfTableGenerator import TDmapLoader
from tqdm import tqdm
import open3d as op3
# from open3d.web_visualizer import draw
from Utils import *
import pandas as pd
from scipy.sparse import csr_matrix
import json

In [6]:
RawTrajs = pd.read_csv('../RawLidarData/Veteran/OutputFile/OutputTrajs/Trajctories.csv')

In [7]:
RawTrajs.columns

Index(['ObjectID', 'FrameIndex', 'Object_Length_mea', 'Object_Width_mea',
       'Object_Height_mea', 'Coord_X_mea', 'Coord_Y_mea', 'Coord_Lon_mea',
       'Coord_Lat_mea', 'Coord_Evel_mea', 'Coord_dis_mea', 'Object_Length_est',
       'Object_Width_est', 'Object_Height_est', 'Coord_X_est', 'Coord_Y_est',
       'Coord_Lon_est', 'Coord_Lat_est', 'Coord_Evel_est', 'Coord_Dis_est',
       'Speed_x', 'Speed_y', 'Speed_est'],
      dtype='object')

In [13]:
TrajGroups = RawTrajs.groupby('ObjectID')
Trajs = [traj[1].loc[:,['Coord_X_est','Coord_Y_est','Coord_Lon_est','Coord_Lat_est','Speed_x','Speed_y']].reset_index(drop = True) for traj in TrajGroups]
Lens = [len(traj) for traj in Trajs]

In [27]:
Label,Attribute = [],[]
for ind,traj in tqdm(enumerate(Trajs)):
    if Lens[ind] > 2:
        for i in range(1,len(traj)):
            labels = traj.iloc[i,[0,1,4,5]]
            attributes = traj.iloc[i-1,[0,1,4,5]]
            Label.append(labels)
            Attribute.append(attributes)
    else:
        continue 

2658it [00:55, 47.61it/s]


In [28]:
Label = pd.concat(Label,axis = 1).T
Attribute = pd.concat(Attribute,axis = 1).T

In [55]:
os.getcwd()

'/Users/czhui960/Documents/Lidar/Lidar_Code'

In [56]:
Label.to_csv('../PosteriorData/Label.csv',index = False)
Attribute.to_csv('../PosteriorData/Attribute.csv',index = False)

In [61]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

In [59]:
Label = Label.reset_index(drop = True)
Attribute = Attribute.reset_index(drop = True)

In [67]:
train_id,test_id = train_test_split(np.arange(len(Label)),test_size = 0.3)
train_id,val_id = train_test_split(train_id,test_size = 0.3)

In [73]:
partition = {
    'train': train_id,
    'validation':val_id,
    'test':test_id
}

In [133]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self,list_IDs,df_attribute, df_label):
        self.list_IDs = list_IDs
        self.df_attribute = df_attribute
        self.df_label = df_label
    def __len__(self):
        return len(self.list_IDs)
    
    def __getitem__(self, index):
        
        index = self.list_IDs[index]
        X = torch.tensor(self.df_attribute.iloc[index])
        y = torch.tensor(self.df_label.iloc[index])
        
        return X.float(),y.float()

In [134]:
class TrackingNet(nn.Module):
    
    def __init__(self):
        super (TrackingNet,self).__init__()
        
        self.fc1 = nn.Linear(4,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,4)
        
    def forward(self,x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        
        return x
        

In [135]:
use_cuda = torch.cuda.is_available()
device = torch.device("cuda:0" if use_cuda else "cpu")
torch.backends.cudnn.benchmark = True

params = {
    'batch_size': 64,
    'shuffle':True,
#     'num_workers':6
}

training_set = Dataset(partition['train'], Attribute, Label)
training_gen = torch.utils.data.DataLoader(training_set,**params)
validation_set = Dataset(partition['validation'], Attribute, Label)
validation_gen = torch.utils.data.DataLoader(validation_set,**params)


In [138]:
loss_func = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(),lr = 0.001)

In [139]:
model = TrackingNet()
model.train()
lrn_rate = 0.005
loss_func = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(),lr = lrn_rate)

for epoch in range(500):
    
    epoch_loss = 0.0
    
    for batch_idx,batch in tqdm(enumerate(training_gen)):
        X,y = batch
        if torch.cuda.is_available():
            X,y = X.cuda(),y.cuda()
            
        optimizer.zero_grad()
        out = model(X)
        loss_train = loss_func(out,y)
        epoch_loss += loss_train.item()
        loss_train.backward()
        optimizer.step()
    
    val_loss = 0.0
    model.eval()
    for batch_idx,batch in tqdm(enumerate(validation_gen)):
        X,y = batch
        if torch.cuda.is_available():
            X,y = X.cuda(),y.cuda()
        
        tar = model(X)
        loss = loss_func(tar,y)
        val_loss += loss.item()
        
    print(f'Epoch {epoch+1} Training Loss: {epoch_loss / len(training_gen)}')
    print(f'Epoch {epoch+1} Validation Loss: {epoch_loss / len(validation_gen)}')

1348it [00:19, 70.39it/s]
578it [00:07, 73.24it/s]
7it [00:00, 61.68it/s]

Epoch 1 Training Loss: 2.3296874378771917
Epoch 1 Validation Loss: 5.433250287644385


1348it [00:21, 64.07it/s]
578it [00:07, 76.52it/s]
7it [00:00, 68.91it/s]

Epoch 2 Training Loss: 0.8397174117650051
Epoch 2 Validation Loss: 1.9583720952581782


1348it [00:18, 73.81it/s]
578it [00:07, 77.95it/s]
8it [00:00, 71.53it/s]

Epoch 3 Training Loss: 0.8610220034371852
Epoch 3 Validation Loss: 2.0080582363898367


1348it [00:18, 73.14it/s]
578it [00:08, 69.17it/s]
7it [00:00, 67.38it/s]

Epoch 4 Training Loss: 0.8448600328198527
Epoch 4 Validation Loss: 1.9703656128739815


1348it [00:18, 72.70it/s]
578it [00:07, 77.79it/s]
7it [00:00, 69.52it/s]

Epoch 5 Training Loss: 0.8263752978593554
Epoch 5 Validation Loss: 1.9272558849730295


1348it [00:18, 73.61it/s]
578it [00:07, 78.16it/s]
7it [00:00, 69.88it/s]

Epoch 6 Training Loss: 0.7987675215020908
Epoch 6 Validation Loss: 1.862869583018717


1348it [00:18, 73.69it/s]
578it [00:07, 78.07it/s]
8it [00:00, 72.01it/s]

Epoch 7 Training Loss: 0.7983531038047476
Epoch 7 Validation Loss: 1.8619030863820063


1348it [00:18, 73.54it/s]
578it [00:07, 77.54it/s]
8it [00:00, 72.76it/s]

Epoch 8 Training Loss: 0.7703849375800669
Epoch 8 Validation Loss: 1.796676290411644


1348it [00:18, 72.45it/s]
578it [00:07, 77.79it/s]
7it [00:00, 68.32it/s]

Epoch 9 Training Loss: 0.7629324695985289
Epoch 9 Validation Loss: 1.7792957941502023


1348it [00:18, 72.86it/s]
578it [00:07, 78.06it/s]
7it [00:00, 69.62it/s]

Epoch 10 Training Loss: 0.7534477829557321
Epoch 10 Validation Loss: 1.7571757983119842


1348it [00:18, 73.40it/s]
578it [00:07, 78.52it/s]
7it [00:00, 69.26it/s]

Epoch 11 Training Loss: 0.7303597189552352
Epoch 11 Validation Loss: 1.7033302788090954


1348it [00:19, 68.64it/s]
578it [00:09, 57.95it/s]
7it [00:00, 67.02it/s]

Epoch 12 Training Loss: 0.738613088568258
Epoch 12 Validation Loss: 1.7225786217820274


1348it [00:19, 70.22it/s]
578it [00:07, 73.77it/s]
8it [00:00, 71.12it/s]

Epoch 13 Training Loss: 0.7339254979497424
Epoch 13 Validation Loss: 1.7116463170177383


1348it [00:19, 70.81it/s]
578it [00:07, 78.71it/s]
8it [00:00, 72.93it/s]

Epoch 14 Training Loss: 0.7049968881969194
Epoch 14 Validation Loss: 1.6441795939263795


1348it [00:18, 74.08it/s]
578it [00:07, 78.32it/s]
7it [00:00, 69.60it/s]

Epoch 15 Training Loss: 0.7180467260233195
Epoch 15 Validation Loss: 1.6746141638052505


1348it [00:18, 73.40it/s]
578it [00:07, 78.12it/s]
8it [00:00, 71.63it/s]

Epoch 16 Training Loss: 0.697317370829844
Epoch 16 Validation Loss: 1.626269577644688


1348it [00:18, 73.07it/s]
578it [00:07, 72.77it/s]
8it [00:00, 74.55it/s]

Epoch 17 Training Loss: 0.7017355287773673
Epoch 17 Validation Loss: 1.636573516940988


1348it [00:22, 60.76it/s]
578it [00:08, 70.00it/s]
7it [00:00, 66.43it/s]

Epoch 18 Training Loss: 0.6970803616761896
Epoch 18 Validation Loss: 1.6257168296531204


1348it [00:18, 73.25it/s]
578it [00:07, 75.32it/s]
7it [00:00, 65.37it/s]

Epoch 19 Training Loss: 0.6905497190561865
Epoch 19 Validation Loss: 1.610486195999549


1348it [00:20, 67.07it/s]
578it [00:08, 66.49it/s]
8it [00:00, 73.01it/s]

Epoch 20 Training Loss: 0.6853126584709752
Epoch 20 Validation Loss: 1.5982724284063574


1348it [00:22, 61.15it/s]
578it [00:09, 62.91it/s]
6it [00:00, 57.16it/s]

Epoch 21 Training Loss: 0.6810419812787446
Epoch 21 Validation Loss: 1.5883124407677296


1348it [00:19, 67.59it/s]
578it [00:08, 67.44it/s]
6it [00:00, 58.90it/s]

Epoch 22 Training Loss: 0.689911104042293
Epoch 22 Validation Loss: 1.608996830880642


93it [00:01, 63.04it/s]


KeyboardInterrupt: 

In [141]:
test_set = Dataset(partition['test'], Attribute, Label)
test_gen = torch.utils.data.DataLoader(test_set,**params)

In [140]:
model.eval()

TrackingNet(
  (fc1): Linear(in_features=4, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=4, bias=True)
)

In [149]:
X,y = test_set[1]

In [150]:
X

tensor([ 36.8646, -30.3895,  -0.2236,  -0.5137])

In [151]:
model(X)

tensor([ 36.7305, -30.4505,  -0.3877,  -0.1461], grad_fn=<AddBackward0>)

In [152]:
y

tensor([ 36.8861, -30.3723,  -0.0524,  -0.2868])

In [57]:
Location = Trajs[2].loc[0,['Coord_Lon_est','Coord_Lat_est']].tolist()
Coords = np.array(Trajs[2].loc[:,['Coord_Lon_est','Coord_Lat_est']])
Lats,Lons = tuple(Coords[:,1]),tuple(Coords[:,0])
gmap = gmplot.gmplot.GoogleMapPlotter(Location[1],Location[0],20)
gmap.apikey = 'AIzaSyDJQ6vklZ0dDaFTRE9tQLWibokU75pTJVY'
gmap.scatter(Lats,Lons,size = 0.5,color = 'g',marker=True)
gmap.plot(Lats,Lons,color = 'r',edge_width = 2)
gmap.draw('./test.html')